workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - ~/.sonar
    environment:
      #android_signing:
      #  - codemagic_keystore
      groups:
        - sonarcloud_credentials
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
        - cd ./Library/Java/JavaVirtualMachines/
        - ls
        - java -version
        - name: Set Android SDK location
          script: |
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
        - chmod +x gradlew
        - ./gradlew assembleRelease    
    artifacts:
        - app/build/outputs/**/*.apk
    #publishing:
    #    email:
    #        recipients:
    #            - user1@example.com
    #            - user2@example.com
    #        notify:
    #          success: true
    #          failure: false   
    #    google_play:                          # For publishing your Android app to Google Play
    #        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #        track: alpha                      # Name of the track: internal, alpha, beta, production
