name: cd-android
on:
  push:
    branches: [develop, release, main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Permisos
      run: chmod +x gradlew
    - name: build release 
      run: ./gradlew build
    - name: build release 
      run: ./gradlew assembleRelease
    - name: Upload App Bundle
      uses: actions/upload-artifact@v1
      with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
  release:
   name: Release App Bundle
   needs: build
   if: github.ref == 'refs/heads/release'
   runs-on: ubuntu-latest
   steps:
     - name: Download from build
       uses: actions/download-artifact@v1
       with:
         name: APK
     - name: Obtener la última versión del release
       id: get_latest_release
       run: |
          # Llamar a la API de GitHub para obtener el último release
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "Último release: $latest_release"

          # Extraer el número de versión y aumentarlo en uno
          version=$(echo $latest_release | cut -c 2-) # Eliminar el prefijo 'v'
          IFS='.' read -r major minor patch <<< "$version"
          ((patch++))
          new_version="v${major}.${minor}.${patch}"

          echo "Nueva versión: $new_version"

          # Establecer la nueva versión como variable de entorno
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
     - name: Crear Release
       id: create_release
       uses: actions/create-release@v1
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}

     - name: Upload Release
       id: upload_release_asset
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: APK/app-debug.apk
         asset_name: ${{ github.event.repository.name }}.apk
         asset_content_type: application/zip
     - run: echo "Upload returned with status=${{ job.status }}."

  prd:
    runs-on: ubuntu-latest
    needs: [build,release]
    if: |
         always() &&
         github.event_name == 'push'  &&
         (needs.release.result == 'success' || needs.release.result == 'skipped') &&
         needs.build.result == 'success' &&
    steps:
    - name: Download from build
      uses: actions/download-artifact@v1
      with:
        name: APK
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: 1:27123300702:android:da91c6d1df6d47180f37cf
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: APK/app-debug.apk