name: cd-android
on:
  push:
    branches: [develop, release, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Permisos
      run: chmod +x gradlew
    #- name: build release 
    #  run: ./gradlew build
    - name: build release 
      run: ./gradlew assembleRelease
    #- name: upload artifact to Firebase App Distribution
    #  uses: wzieba/Firebase-Distribution-Github-Action@v1
    #  with:
    #    appId: 1:27123300702:android:da91c6d1df6d47180f37cf
    #    serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
    #    groups: testers
    #    file: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload App Bundle
      uses: actions/upload-artifact@v1
      with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
  release:
   name: Release App Bundle
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: Download from build
       uses: actions/download-artifact@v1
       with:
         name: APK
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: v1.0.1
         release_name: Release v1.0.1

     - name: Upload Release
       id: upload_release_asset
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: aab/app-release.aab
         asset_name: ${{ github.event.repository.name }}.aab
         asset_content_type: application/zip
     - run: echo "Upload returned with status=${{ job.status }}."

